# Generated by Django 4.2.2 on 2023-06-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.URLField()),
                ('titulo_proyecto', models.CharField(max_length=200)),
                ('descripcion_proyecto', models.TextField()),
                ('tags', models.CharField(max_length=200)),
                ('url_github', models.URLField()),
            ],
        ),
    ]
