# Generated by Django 4.2.2 on 2023-06-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proyecto',
            table='proyecto',
        ),
    ]
